# **ASSIGNMENT 3**

**Question 1**

In [3]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

**Question 2**

In [ ]:
lst1=[]
lst2=[]
print("List 1")
for i in range(0,5):
  l=int(input())
  lst1.append(l)
print("List 2")
for i in range(0,5):
  m=int(input())
  lst2.append(m)  

print("Lists")
print(lst1)
print(lst2)
a=np.array(lst1)   # list to array
b=np.array(lst2)
print("Numpy Arrays")
print(a)
print(b)
print("Concatenated array")
x=np.concatenate((a,b))
print(x)
print("Sorted Array",np.sort(x))


List 1
6
5
7
4
3
List 2
8
9
1
2
10
Lists
[6, 5, 7, 4, 3]
[8, 9, 1, 2, 10]
Numpy Arrays
[6 5 7 4 3]
[ 8  9  1  2 10]
Concatenated array
[ 6  5  7  4  3  8  9  1  2 10]
Sorted Array [ 1  2  3  4  5  6  7  8  9 10]


**Question 3**

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("type of array:",arr.dtype)
print("Size of array:",arr.size) 
print("Shape:",arr.shape) #Shape of array
print("Dimensions:",arr.ndim) # array dimension

type of array: int64
Size of array: 9
Shape: (3, 3)
Dimensions: 2


**Question 4**

1-d array can be converted to 2-d array using np.newaxis or np.expand_dims. They basically add an axis to the array. If np.newaxis is used once then one dimension is increased i.e 1D to 2D, 2D to 3D. 

In [ ]:
a=np.arange(6)
print(a)
print("dimension of a:",a.ndim)
print("Shape of a:",a.shape)
#using new-axis
a1= a[np.newaxis,:]
print("Shape of a1:",a1.shape)
print("dimension of a1:",a1.ndim)

[0 1 2 3 4 5]
dimension of a: 1
Shape of a: (6,)
Shape of a1: (1, 6)
dimension of a1: 2


In [ ]:
a=np.arange(6)
print(a)
print("dimension of a:",a.ndim)
print("Shape of a:",a.shape)
#using expand dims
a1= np.expand_dims(a,axis=0)
print("Shape of a1:",a1.shape)
print("dimension of a1:",a1.ndim)

[0 1 2 3 4 5]
dimension of a: 1
Shape of a: (6,)
Shape of a1: (1, 6)
dimension of a1: 2


**Question 5**

In [5]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print("Vertical",np.vstack((a1,a2))) 
print("Horizontal",np.hstack((a1,a2)))

Vertical [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal [[1 2 5 6]
 [3 4 7 8]]


**Question 6**

Unique value can be found using np.unique().The unique function contains one arguement **return_counts** which is set to True. It will return all the unique values from the array.

In [7]:
a = np.array([1, 1, 2, 3, 4, 4, 1])
b = np.unique(a, return_counts=True)
print(b)

(array([1, 2, 3, 4]), array([3, 1, 1, 2]))
